#create_secion_pages

import requests
from datetime import datetime

import re

import PASS

graphURI = 'https://graph.microsoft.com/'

def parse_token(full_token):
    p = re.search('=(.*?)&', full_token) #regex for between = and &. re.search gets the values between
    return p.group(1)

def msgraph_request(resource, requestHeaders):
    # Request
    results = requests.get(resource, headers=requestHeaders).json()
    return results

def main():
    full_token_url = PASS.token_current #the entire url that shows up after navigating to the url generated by access_token_url
    token_parsed = parse_token(full_token_url)

    requestHeaders = {'Authorization': 'Bearer ' + token_parsed}

    middle_url = 'v1.0/me/onenote/'
    full_url = graphURI + middle_url + 'notebooks'

    notebooks = msgraph_request(full_url,requestHeaders)

    notebooks_list = notebooks['value'] #some metadata in the notebooks json outside of value
    for notebook in notebooks_list:
        display_name = notebook['displayName']
        print(display_name)
        if display_name == "Andrew's Notebook":
            notebook_id = notebook['id']
            sections_url = graphURI + middle_url + 'notebooks/' + notebook_id + '/sections'
            sections = msgraph_request(sections_url,requestHeaders)
            #print(sections)
            sections_list = sections['value']
            for section in sections_list:
                section_name = section['displayName']
                section_id = section['id']
                print("ID:"+section_id+" Name:"+section_name)
                

    return 0

main()
exit()