import requests
from datetime import datetime

import re

import PASS
def parse_token(full_token):
    p = re.search('=(.*?)&', full_token) #regex for between = and &. re.search gets the values between
    return p.group(1)

def main():
    full_token_url = PASS.token_current #the entire url that shows up after navigating to the url generated by access_token_url
    token_parsed = parse_token(full_token_url)
    requestHeaders = {'Authorization': 'Bearer ' + token_parsed, 'Content-Type': 'text/html'}
    # requestHeaders = {'Authorization': token_parsed}


    #open text file in read mode
    text_file = open("C:\\Users\\acook\OneDrive\Documents\Programming\evernote-export\IGNORE_evernote_note.txt", "r")
    
    #read whole file to a string
    data = text_file.read()
    print(data)
    #close file
    


    section_id = '0-2170C8CE0F8F3556!82608'
    url = 'https://graph.microsoft.com/v1.0/me/onenote/sections/'+section_id+'/pages'
    post_request = 'Content-type: multipart/form-data; boundary=MyPartBoundary198374 Content-Disposition:form-data; name="Presentation" Content-Type:text/html'
    post_request = post_request + data

    test_data = '''
<!DOCTYPE html>
<html>
  <head>
    <title>A page with <i>rendered</i> images and an <b>attached</b> file</title>
    <meta name="created" content="2015-07-22T09:00:00-08:00" />
  </head>
  <body>
    <p>Here's an image from an online source:</p>
    <img src="https://..." alt="an image on the page" width="500" />
    <p>Here's an image uploaded as binary data:</p>
    <img src="name:imageBlock1" alt="an image on the page" width="300" />
    <p>Here's a file attachment:</p>
    <object data-attachment="FileName.pdf" data="name:fileBlock1" type="application/pdf" />
  </body>
</html>
    '''


    results = requests.post(url, data, headers=requestHeaders)  #get(resource, headers=requestHeaders).json()
    print(results.json())
    text_file.close()

main()
exit()